# Generated by Django 3.1.4 on 2025-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20250213_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
