# Generated by Django 3.1.4 on 2025-02-13 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'ordering': ['-created_at'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='rolepermissions',
            options={'ordering': ['-created_at'], 'verbose_name': 'RolePermission', 'verbose_name_plural': 'RolePermissions'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['-created_at'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='userpermissions',
            options={'ordering': ['-created_at'], 'verbose_name': 'UserPermission', 'verbose_name_plural': 'UserPermissions'},
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolepermissions', to='users.roles'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
