# Generated by Django 3.1.4 on 2025-05-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250320_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='file',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
