# Generated by Django 3.1.4 on 2025-05-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='file',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
