# Generated by Django 3.1.4 on 2025-02-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('log_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Purchase Return', 'Purchase Return'), ('Sales Return', 'Sales Return'), ('Damage', 'Damage'), ('Transfer', 'Transfer'), ('Adjustment', 'Adjustment'), ('Opening', 'Opening')], default='None', max_length=50)),
                ('reference', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock History',
                'db_table': 'products_stock_history',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_qty', models.FloatField(default=0)),
                ('sold_qty', models.FloatField(default=0)),
                ('hold_qty', models.FloatField(default=0)),
                ('available_qty', models.FloatField(default=0)),
                ('transfering_qty', models.FloatField(default=0)),
                ('warranty', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('discount_percentage', models.FloatField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stocks_branch', related_query_name='stock_stocks_branch', to='branch.branch')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_stocks', to='catalog.brand')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_stocks', to='catalog.colorvariation')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'products_stocks',
            },
        ),
    ]
