# Generated by Django 3.1.4 on 2025-02-13 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20250213_0519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20250213_0519'),
        ('stock', '0001_initial'),
        ('branch', '0002_auto_20250213_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stocks_created_by', related_query_name='stock_stocks_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.product'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_stocks', to='catalog.attributevariation'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productunit_stocks', to='catalog.productunit'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stocks_updated_by', related_query_name='stock_stocks_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockhistory_branch', related_query_name='stock_stockhistory_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockhistory_created_by', related_query_name='stock_stockhistory_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stocks'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockhistory_updated_by', related_query_name='stock_stockhistory_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stocks',
            index=models.Index(fields=['-product', '-created_at'], name='products_stocks_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['-stock', '-created_at'], name='products_st_stock_i_995659_idx'),
        ),
    ]
