# Generated by Django 3.1.4 on 2025-02-19 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250219_0534'),
        ('stock', '0002_auto_20250213_0519'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stocks',
            name='products_stocks_idx',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='color',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='size',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='uom',
        ),
        migrations.AddField(
            model_name='stocks',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.productvariantattribute'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='stocks',
            index=models.Index(fields=['-product_variant', '-created_at'], name='products_stocks_idx'),
        ),
    ]
