# Generated by Django 3.1.4 on 2025-02-19 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_merge_20250217_0810'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_auto_20250219_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('reason', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockadjustment_branch', related_query_name='stock_stockadjustment_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockadjustment_created_by', related_query_name='stock_stockadjustment_created_by', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='stock.stocks')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_stockadjustment_updated_by', related_query_name='stock_stockadjustment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'db_table': 'stock_adjustment',
            },
        ),
    ]
