# Generated by Django 3.1.4 on 2025-02-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250219_0534'),
        ('stock', '0004_stockadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.productvariantattribute'),
        ),
    ]
