# Generated by Django 3.1.4 on 2025-03-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20250219_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
