# Generated by Django 3.1.4 on 2025-02-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expense_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.FloatField(default=0)),
                ('reason', models.CharField(blank=True, help_text='purchase, loan, advance, agreemnt, etc', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'AdditionalExpense',
                'verbose_name_plural': 'AdditionalExpenses',
                'db_table': 'additionalexpenses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('vat_amount', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('due_amount', models.FloatField(default=0)),
                ('invoice_no', models.CharField(max_length=20, unique=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchase',
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('purchase_quantity', models.FloatField(default=0)),
                ('demaged_quantity', models.FloatField(default=0)),
                ('good_quantity', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('warranty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchase Histories',
                'db_table': 'purchase_history',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_no', models.CharField(max_length=30, unique=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('total_return_qty', models.FloatField(default=0)),
                ('total_refund_amount', models.FloatField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'db_table': 'purchase_return',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_qty', models.FloatField(default=0)),
                ('refund_amount', models.FloatField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_purchasereturnhistory_branch', related_query_name='purchase_purchasereturnhistory_branch', to='branch.branch')),
            ],
            options={
                'verbose_name': 'Purchase Return History',
                'verbose_name_plural': 'Purchase Return Histories',
                'db_table': 'purchase_return_history',
            },
        ),
    ]
