# Generated by Django 3.1.4 on 2025-02-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250219_0534'),
        ('purchase', '0004_auto_20250213_0534'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchasehistory',
            name='purchase_hi_product_41a27c_idx',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='size',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='uom',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_history', to='products.productvariantattribute'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['-product_variant', '-created_at'], name='purchase_hi_product_8d1b7a_idx'),
        ),
    ]
