# Generated by Django 3.1.4 on 2025-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20250412_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_amount_wiv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='vat_amounts',
            field=models.FloatField(default=0),
        ),
    ]
