# Generated by Django 3.1.4 on 2025-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20250426_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_amount_wiv',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='total_amount_iv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='total_amount_wv',
            field=models.FloatField(default=0),
        ),
    ]
