# Generated by Django 3.1.4 on 2025-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20250527_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Select Payment Method', 'Select Payment Method'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay'), ('Partial-Due', 'Partial-Due'), ('Due', 'Due')], default='Select Payment Method', max_length=100),
        ),
    ]
