# Generated by Django 3.1.4 on 2025-05-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20250529_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='paid_on_date',
            new_name='paid_on',
        ),
    ]
