# Generated by Django 3.1.4 on 2025-02-18 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_auto_20250213_0525'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_auto_20250213_0519'),
        ('branch', '0004_merge_20250217_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('vat_amount', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('due_amount', models.FloatField(default=0)),
                ('invoice_no', models.CharField(max_length=20, unique=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_sale_branch', related_query_name='sell_sale_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_sale_created_by', related_query_name='sell_sale_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_sale_updated_by', related_query_name='sell_sale_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sale',
                'db_table': 'sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('warranty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salehistory_branch', related_query_name='sell_salehistory_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salehistory_created_by', related_query_name='sell_salehistory_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_history', to='stock.stocks')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_history', to='sell.sale')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salehistory_updated_by', related_query_name='sell_salehistory_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale_History',
                'verbose_name_plural': 'sale_historys',
                'db_table': 'sale_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_no', models.CharField(max_length=30, unique=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('total_return_qty', models.FloatField(default=0)),
                ('total_refund_amount', models.FloatField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salereturn_branch', related_query_name='sell_salereturn_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salereturn_created_by', related_query_name='sell_salereturn_created_by', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_returns', to='sell.sale')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salereturn_updated_by', related_query_name='sell_salereturn_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale Return',
                'verbose_name_plural': 'Sale Returns',
                'db_table': 'sale_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_qty', models.FloatField(default=0)),
                ('refund_amount', models.FloatField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salereturnhistory_branch', related_query_name='sell_salereturnhistory_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salereturnhistory_created_by', related_query_name='sell_salereturnhistory_created_by', to=settings.AUTH_USER_MODEL)),
                ('sale_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_return_details', to='sell.salehistory')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_return_details', to='sell.salereturn')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_salereturnhistory_updated_by', related_query_name='sell_salereturnhistory_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale Return History',
                'verbose_name_plural': 'Sale Return Histories',
                'db_table': 'sale_return_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='salereturnhistory',
            index=models.Index(fields=['-sale_return', 'sale_history', '-created_at'], name='sale_return_sale_re_644b82_idx'),
        ),
        migrations.AddIndex(
            model_name='salereturn',
            index=models.Index(fields=['-sale', '-created_at'], name='sale_return_sale_id_303399_idx'),
        ),
        migrations.AddIndex(
            model_name='salehistory',
            index=models.Index(fields=['-product', 'sale', '-created_at'], name='sale_histor_product_b53178_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-customer', '-created_at'], name='sale_custome_96f3f0_idx'),
        ),
    ]
