# Generated by Django 3.1.4 on 2025-02-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale_History', 'verbose_name_plural': 'sale Historys'},
        ),
    ]
