# Generated by Django 3.1.4 on 2025-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20250218_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='salehistory',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
    ]
