# Generated by Django 3.1.4 on 2025-04-12 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0005_remove_branch_company_name'),
        ('stock', '0007_auto_20250308_0813'),
        ('contacts', '0003_auto_20250213_0525'),
        ('sell', '0008_auto_20250412_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('discount_type', models.CharField(choices=[('Select Type', 'Select Type'), ('Percentage', 'Percentage'), ('Flat', 'Flat')], default='Select Type', max_length=100)),
                ('payment_method', models.CharField(choices=[('Select Payment Method', 'Select Payment Method'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay')], default='Select Payment Method', max_length=100)),
                ('vat_amount', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('due_amount', models.FloatField(default=0)),
                ('invoice_no', models.CharField(max_length=20, unique=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_quotation_branch', related_query_name='sell_quotation_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_quotation_created_by', related_query_name='sell_quotation_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_quotation_updated_by', related_query_name='sell_quotation_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotation',
                'db_table': 'quotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('selling_price', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('discount_type', models.CharField(choices=[('Select Type', 'Select Type'), ('Percentage', 'Percentage'), ('Flat', 'Flat')], default='Select Type', max_length=100)),
                ('warranty', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_quotationhistory_branch', related_query_name='sell_quotationhistory_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_quotationhistory_created_by', related_query_name='sell_quotationhistory_created_by', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_history', to='stock.stocks')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_history', to='sell.quotation')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_quotationhistory_updated_by', related_query_name='sell_quotationhistory_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation_History',
                'verbose_name_plural': 'quotation Historys',
                'db_table': 'quotation_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quotationhistory',
            index=models.Index(fields=['-product_variant', 'quotation', '-created_at'], name='quotation_h_product_e44934_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['-customer', '-created_at'], name='quotation_custome_65a1de_idx'),
        ),
    ]
