# Generated by Django 3.1.4 on 2025-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_auto_20250412_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_amount_wiv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salehistory',
            name='vat_amounts',
            field=models.FloatField(default=0),
        ),
    ]
