# Generated by Django 3.1.4 on 2025-05-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_auto_20250527_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sell_date',
            new_name='sale_date',
        ),
    ]
