# Generated by Django 3.1.4 on 2025-05-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0013_auto_20250527_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='paid_on',
            new_name='paid_on_date',
        ),
    ]
