# Generated by Django 3.1.4 on 2025-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0015_auto_20250529_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
