# Generated by Django 3.1.4 on 2025-05-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0016_auto_20250529_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationhistory',
            name='total_amount_iv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotationhistory',
            name='total_amount_wv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quotationhistory',
            name='vat_amounts',
            field=models.FloatField(default=0),
        ),
    ]
