# Generated by Django 3.1.4 on 2025-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0017_auto_20250531_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='payment_method',
            field=models.CharField(choices=[('Select Payment Method', 'Select Payment Method'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay'), ('Partial-Due', 'Partial-Due'), ('Due', 'Due')], default='Select Payment Method', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Select Payment Method', 'Select Payment Method'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay'), ('Partial-Due', 'Partial-Due'), ('Due', 'Due')], default='Select Payment Method', max_length=100),
        ),
    ]
