# Generated by Django 3.1.4 on 2025-02-13 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0002_auto_20250213_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_subcategory_created_by', related_query_name='catalog_subcategory_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_subcategory_updated_by', related_query_name='catalog_subcategory_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_productunit_branch', related_query_name='catalog_productunit_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_productunit_created_by', related_query_name='catalog_productunit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_productunit_updated_by', related_query_name='catalog_productunit_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colorvariation',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_colorvariation_branch', related_query_name='catalog_colorvariation_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='colorvariation',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_colorvariation_created_by', related_query_name='catalog_colorvariation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colorvariation',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_colorvariation_updated_by', related_query_name='catalog_colorvariation_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_category_branch', related_query_name='catalog_category_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_category_created_by', related_query_name='catalog_category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_category_updated_by', related_query_name='catalog_category_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_brand_branch', related_query_name='catalog_brand_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_brand_created_by', related_query_name='catalog_brand_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_brand_updated_by', related_query_name='catalog_brand_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributevariation',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_attributevariation_branch', related_query_name='catalog_attributevariation_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='attributevariation',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_attributevariation_created_by', related_query_name='catalog_attributevariation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributevariation',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_attributevariation_updated_by', related_query_name='catalog_attributevariation_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
