# Generated by Django 3.1.4 on 2025-02-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20250213_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevariation',
            options={'ordering': ['-created_at'], 'verbose_name': 'AttributeVariation', 'verbose_name_plural': 'AttributeVariations'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterModelOptions(
            name='colorvariation',
            options={'ordering': ['-created_at'], 'verbose_name': 'ColorVariation', 'verbose_name_plural': 'ColorVariations'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['-created_at'], 'verbose_name': 'ProductUnit', 'verbose_name_plural': 'ProductUnits'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategorys'},
        ),
    ]
