# Generated by Django 3.1.4 on 2025-04-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20250213_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vat_amounts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='vat_percentage',
            field=models.FloatField(default=0),
        ),
    ]
