# Generated by Django 3.1.4 on 2025-05-31 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0005_remove_branch_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_logo', models.JSONField(blank=True, default=list, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('invoice_email', models.BooleanField(default=False)),
                ('assign_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch')),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_invoicesetting_branch', related_query_name='setting_invoicesetting_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_invoicesetting_created_by', related_query_name='setting_invoicesetting_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_invoicesetting_updated_by', related_query_name='setting_invoicesetting_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('software_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_logo', models.JSONField(blank=True, default=list, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('favicon_icon', models.JSONField(blank=True, default=list, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_email', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=500)),
                ('email_host', models.CharField(blank=True, max_length=500, null=True)),
                ('email_port', models.IntegerField(blank=True, null=True)),
                ('email_use_tls', models.BooleanField(default=False)),
                ('email_host_user', models.CharField(blank=True, max_length=500, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=500, null=True)),
                ('email_active', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_generalsetting_branch', related_query_name='setting_generalsetting_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_generalsetting_created_by', related_query_name='setting_generalsetting_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_generalsetting_updated_by', related_query_name='setting_generalsetting_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarcodeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('barcode_enable', models.BooleanField(default=False)),
                ('barcode_logo', models.JSONField(blank=True, default=list, null=True)),
                ('assign_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch')),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_barcodesetting_branch', related_query_name='setting_barcodesetting_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_barcodesetting_created_by', related_query_name='setting_barcodesetting_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_barcodesetting_updated_by', related_query_name='setting_barcodesetting_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('banner_image', models.JSONField(blank=True, default=list)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_bannersetting_created_by', related_query_name='setting_bannersetting_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_bannersetting_updated_by', related_query_name='setting_bannersetting_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
