# Generated by Django 3.1.4 on 2025-04-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesetting',
            name='invoice_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='invoice_image/'),
        ),
        migrations.AlterField(
            model_name='barcodesetting',
            name='barcode_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='barcode_image/'),
        ),
    ]
