# Generated by Django 3.1.4 on 2025-04-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20250416_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodesetting',
            name='barcode_image',
        ),
        migrations.AddField(
            model_name='barcodesetting',
            name='barcode_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='barcode_logo/'),
        ),
        migrations.AlterField(
            model_name='invoicesetting',
            name='invoice_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='invoice_logo/'),
        ),
    ]
