# Generated by Django 3.1.4 on 2025-04-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_remove_branch_company_name'),
        ('setting', '0004_bannersetting_emailsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodesetting',
            name='assign_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch'),
        ),
    ]
