# Generated by Django 3.1.4 on 2025-02-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branchs',
                'db_table': 'branchs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=500, null=True)),
                ('country_code', models.CharField(blank=True, max_length=500, null=True)),
                ('country_short_name', models.CharField(blank=True, max_length=500, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_country_branch', related_query_name='branch_country_branch', to='branch.branch')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
                'db_table': 'countrys',
                'ordering': ['-id'],
            },
        ),
    ]
