# Generated by Django 3.1.4 on 2025-02-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20250213_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branchs'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countrys'},
        ),
    ]
