# Generated by Django 3.1.4 on 2025-02-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_initial'),
        ('branch', '0003_auto_20250213_0525'),
    ]

    operations = [
    ]
