# Generated by Django 3.1.4 on 2025-03-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_merge_20250217_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='company_name',
        ),
    ]
