# Generated by Django 3.1.4 on 2025-03-01 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0004_merge_20250217_0810'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsutomizeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('topics', models.CharField(blank=True, choices=[('None', 'None'), ('Sale', 'Sale'), ('Sale Return', 'Sale Return'), ('Stock Transfer', 'Stock Adjustment'), ('Purchase', 'Purchase'), ('Purchase Return', 'Purchase Return'), ('Valentines', 'Valentines'), ('Pohela Baishak', 'Pohela Baishak'), ('Eid', 'Eid'), ('Ramadan', 'Ramadan'), ('Special', 'Special'), ('Other', 'Other')], default='None', max_length=500, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_csutomizemessage_branch', related_query_name='notifications_csutomizemessage_branch', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_csutomizemessage_created_by', related_query_name='notifications_csutomizemessage_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_csutomizemessage_updated_by', related_query_name='notifications_csutomizemessage_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
