# Generated by Django 3.1.4 on 2025-02-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to='products/')),
                ('weight', models.FloatField(default=0, help_text='Grams')),
                ('product_type', models.CharField(choices=[('None', 'None'), ('Single', 'Single'), ('Variable', 'Variable'), ('Combo', 'Combo')], default='None', max_length=20)),
                ('country', models.CharField(help_text='Which countrys product', max_length=100)),
                ('vat_percentage', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_status', models.CharField(choices=[('Sold', 'Sold'), ('Purchased', 'Purchased'), ('Sales Return', 'Sales Return'), ('Purchase Return', 'Purchase Return'), ('Damage', 'Damage')], default=None, max_length=50)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('barcode', models.CharField(max_length=1000, unique=True)),
                ('barcode_image', models.ImageField(blank=True, default=None, null=True, upload_to='barcodes/')),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('sales_return_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_return_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Product Barcode',
                'verbose_name_plural': 'Product Barcodes',
                'db_table': 'product_barcodes',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_productvariantattribute_branch', related_query_name='products_productvariantattribute_branch', to='branch.branch')),
                ('color_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.colorvariation')),
            ],
            options={
                'verbose_name': 'ProductVariantAttribute',
                'verbose_name_plural': 'ProductVariantAttributes',
                'db_table': 'productvariantattributes',
                'ordering': ['-id'],
            },
        ),
    ]
