# Generated by Django 3.1.4 on 2025-02-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250213_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantattribute',
            options={'ordering': ['-created_at'], 'verbose_name': 'ProductVariantAttribute', 'verbose_name_plural': 'ProductVariantAttributes'},
        ),
    ]
