# Generated by Django 3.1.4 on 2025-02-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250213_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='quantity',
        ),
    ]
