# Generated by Django 3.1.4 on 2025-02-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariantattribute_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbarcodes',
            old_name='product',
            new_name='product_variant',
        ),
    ]
