# Generated by Django 3.1.4 on 2025-02-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20250219_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcodes',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariantattribute'),
        ),
    ]
