# Generated by Django 3.1.4 on 2025-02-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20250219_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantattribute',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
