# Generated by Django 3.1.4 on 2025-02-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250219_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcodes',
            name='barcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbarcodes',
            name='product_status',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Purchased', 'Purchased'), ('Sales', 'Sales'), ('Sales Return', 'Sales Return'), ('Purchase Return', 'Purchase Return'), ('Damage', 'Damage')], default=None, max_length=50),
        ),
    ]
