# Generated by Django 3.1.4 on 2025-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20250220_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcodes',
            name='barcode_image',
            field=models.JSONField(default=list),
        ),
    ]
