# Generated by Django 3.1.4 on 2025-02-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20250220_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcodes',
            name='barcode',
            field=models.CharField(default=1, max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbarcodes',
            name='barcode_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='barcodes/'),
        ),
    ]
