# Generated by Django 3.1.4 on 2025-02-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20250220_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcodes',
            name='product_status',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Purchased', 'Purchased'), ('Sales Return', 'Sales Return'), ('Purchase Return', 'Purchase Return'), ('Damage', 'Damage')], default=None, max_length=50),
        ),
    ]
