# Generated by Django 3.1.4 on 2025-02-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20250225_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbarcodes',
            name='mark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
