# Generated by Django 3.1.4 on 2025-02-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productbarcodes_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbarcodes',
            old_name='mark',
            new_name='inv',
        ),
    ]
