# Generated by Django 3.1.4 on 2025-04-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20250315_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcodes',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
