# Generated by Django 3.1.4 on 2025-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20250412_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbarcodes',
            name='inv_quotation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
