# Generated by Django 3.1.4 on 2025-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20250418_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbarcodes',
            name='inv_return_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
