# Generated by Django 3.1.4 on 2025-04-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productbarcodes_inv_return_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_amount',
            field=models.FloatField(default=0),
        ),
    ]
