# Generated by Django 3.1.4 on 2025-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
