# Generated by Django 3.1.4 on 2025-05-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, help_text='Which countrys product', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Single', 'Single'), ('Variable', 'Variable'), ('Combo', 'Combo')], default='None', max_length=20, null=True),
        ),
    ]
